#!/usr/bin/Rscript
## -*- mode: R -*-
## code to build ESSR environemnt.
## Assume that current directory is etc/ESSR
## run "./BUILDESSR" to create ../ESSR.rda

## exactly as in inferior-ess-r-load-ESSR in ess-r-d.el
source('./R/.load.R', local=TRUE)
ESSR <- .ess.load.ESSR('./R/')
saveRDS(ESSR, file = "../ESSR.rds")
